### ISSUE TITLE
HB-UNI-Sen-LEV-TOF - Issue

### ISSUE THREAD

**Issue by Passagier** [jp112sdl/HB-UNI-Sen-LEV-TOF#1]
Hallo Jerome,

habe den HB-UNI-Sen-LEV-TOF nachgebaut, Hardware funktioniert mir anderen Sketchen vollständig (getestet, auch Abstandsmessung), aber mit diesem Sketch bekomme ich aus der serielle Ausgabe lediglich: AskSAskS (Ausgabe müsste von der Akssin sein)
Mit diesem Sketch läufts noch nicht bei mir, evtl. andere Library(?) oder hast Du evtl. eine Idee?

**Comment by jp112sdl** [comment]
> AskSAskS (Ausgabe müsste von der Akssin sein)

Das Problem ist, dass der Sketch noch während der Ausgabe der Initialmeldung abstürzt

Kommentier mal hier das `vl53l0x.init();` aus:
https://github.com/jp112sdl/HB-UNI-Sen-LEV-TOF/blob/ae6d07fb8a74e5c2d791c49386c9ada14d37d033/HB-UNI-Sen-LEV-TOF.ino#L238


Startet das Gerät dann erstmal?

**Comment by Passagier** [comment]
Ja das klappt.
Welche Library für vl53l0 verwendest du - einige lassen sich mit dem Sketch nicht kompilieren?

**Comment by jp112sdl** [comment]
Und dein Sensor hat die Adresse `0x29` ?

Viel mehr fällt mir dann auch nicht ein. 
Hab das Dingens nicht im Einsatz. 
War damals nur ein Versuch.

**Comment by jp112sdl** [comment]
Lib ist https://github.com/pololu/vl53l0x-arduino

**Comment by Passagier** [comment]
Adresse 0x29 Passt, gleiche Library, habe sie mal rausgelöscht und von deinem Link wieder neu reingeholt,
die Beispiele der Library funktionieren, es wird korrekt gemessen, das muss irgendwie mit der Asksin, der VX-Lib und deinem Sketch zusammenhängen, sobald das init auslöst, bleibt alles hängen.

**Comment by jp112sdl** [comment]
Schreib mal ins setup() noch vor
https://github.com/jp112sdl/HB-UNI-Sen-LEV-TOF/blob/ae6d07fb8a74e5c2d791c49386c9ada14d37d033/HB-UNI-Sen-LEV-TOF.ino#L271
die Zeile
`Wire.begin();`

**Comment by Passagier** [comment]
Hallo Jerome,

wie ein Chirurg präzise Lösung, hat funktioniert, danke :)
